world =["FIFA World Cup qualification", "FIFA World Cup", "Island Games", "Confederations Cup", "CONIFA World Football Cup",
        "Nehru Cup", "Olympic Games", "Viva World Cup", "Coupe de l'Outre-Mer", "Lunar New Year Cup", "FIFA Series",
        "Kirin Challenge Cup", "Millennium Cup", "Inter-Allied Games", "King Hassan II Tournament", "FIFI Wild Cup", "VFF Cup",
        "Mundialito", "Nations Cup", "Afro-Asian Games", "Dragon Cup", "OSN Cup", "World Unity Cup", "CONMEBOL–UEFA Cup of Champions",
        "Four Nations' Cup", "Cup of Ancient Civilizations", "ConIFA Challenger Cup", "Real Madrid 75th Anniversary Cup",
        "FIFA 75th Anniversary Cup", "The Other Final", "Benedikt Fontana Cup"]
continental = ["UEFA Euro qualification", "African Cup of Nations qualification",
               "Copa América", "African Cup of Nations", "AFC Asian Cup qualification",
               "UEFA Nations League", "CONCACAF Nations League", "AFC Asian Cup", "Gold Cup", "UEFA Euro",
               "Asian Games", "CONCACAF Championship", "CONCACAF Championship qualification", "Oceania Nations Cup",
               "AFC Challenge Cup", "AFC Challenge Cup qualification", "Gold Cup qualification", "All-African Games",
               "Cyprus International Tournament", "CONCACAF Nations League qualification", "Central American and Caribbean Games",
               "Oceania Nations Cup qualification", "Malta International Tournament", "CONIFA European Football Cup",
               "Copa Chevallier Boutell", "Merlion Cup", "Pacific Mini Games", "Bolivarian Games", "MSG Prime Minister's Cup",
               "Atlantic Cup", "Tournoi de France", "Copa América qualification", "Marlboro Cup", "Superclásico de las Américas",
               "Mapinduzi Cup", "NAFC Championship", "CONIFA World Football Cup qualification", "CONIFA Asia Cup", "NAFU Championship", "CONIFA Africa Football Cup",
               "CONIFA South America Football Cup", "ASEAN Championship qualification"]
regional = ["CECAFA Cup", "CFU Caribbean Cup qualification", "Merdeka Tournament",
            "British Home Championship", "Gulf Cup", "COSAFA Cup", "AFF Championship", "Nordic Championship",
            "CFU Caribbean Cup", "King's Cup", "Amílcar Cabral Cup", "Muratti Vase", "South Pacific Games",
            "Southeast Asian Games", "UNCAF Cup", "SAFF Cup", "Korea Cup", "Arab Cup", "EAFF Championship",
            "Central European International Cup", "CCCF Championship", "WAFF Championship", "Indian Ocean Island Games",
            "Baltic Cup", "Windward Islands Tournament", "Balkan Cup", "Kirin Cup", "Indonesia Tournament", "Pacific Games",
            "UDEAC Cup", "South Asian Games", "Southeast Asian Peninsular Games", "AFF Championship qualification",
            "Vietnam Independence Cup", "Palestine Cup", "West African Cup", "South Pacific Mini Games", "Pan American Championship",
            "USA Cup", "Brazil Independence Cup", "Far Eastern Championship Games", "Dynasty Cup", "Copa Lipton",
            "COSAFA Cup qualification", "ASEAN Championship", "Copa Newton", "Arab Cup qualification", "Copa Roca", "Copa Paz del Chaco",
            "Prime Minister's Cup", "ABCS Tournament", "Inter Games Football Tournament", "Copa del Pacífico", "Copa Rio Branco",
            "East Asian Games", "Intercontinental Cup", "Simba Tournament", "Jordan International Tournament", "Copa Oswaldo Cruz",
            "ELF Cup", "Copa Carlos Dittborn", "Copa Juan Pinto Durán", "Kuneitra Cup", "Copa Premio Honor Uruguayo",
            "UNIFFAC Cup", "GaNEFo", "Nile Basin Tournament", "Copa Artigas", "Copa Premio Honor Argentino", "Miami Cup","Rous Cup",
            "SKN Football Festival", "Tournament Burkina Faso", "CAFA Nations Cup", "Copa Bernardo O'Higgins", "Beijing International Friendship Tournament",
            "Four Nations Tournament", "Mahinda Rajapaksa Cup", "Tri Nation Tournament", "Copa Ramón Castilla", "Copa Félix Bogado",
            "Tynwald Hill Tournament", "Mauritius Four Nations Cup", "EAFF Championship qualification", "Joe Robbie Cup", "Great Wall Cup",
            "Corsica Cup", "Dakar Tournament", "Phillip Seaga Cup", "Three Nations Cup", "Zambian Independence Tournament",
            "Hungary Heritage Cup", "Niamh Challenge Cup", "Tri-Nations Series", "Marianas Cup", "Atlantic Heritage Cup",
            "Open International Championship", "Copa Confraternidad", "TIFOCO Tournament", "Évence Coppée Trophy"]
friendly = ["Friendly", "African Friendship Games", "United Arab Emirates Friendship Tournament", "Peace Cup", "Navruz Cup", "Scania 100 Tournament",
            "Guangzhou International Friendship Tournament"]